### ISSUE TITLE
EUZ adjusted price enhancement

### ISSUE THREAD

**Issue by Ltty** [TheEconomist/big-mac-data#21]
Hi,

Are the big mac prices really the same in the entire Euro zone, and if so, shouldn't be there a difference between a Big Mac in Germany and Slovenia or Greece for example?

I would assume that based on the GDP per capita there should be a difference that could be calculated for EUR countries.

Is this something you could consider for a future update?

Thanks,
Florian

**Comment by roxwillis** [comment]
Big Mac prices differ across the euro area. The price we use is a GDP-weighted average of member countries.
