### ISSUE TITLE
Calclation for Lebanon is wrong

### ISSUE THREAD

**Issue by Ltty** [TheEconomist/big-mac-data#22]
According to the conversion data for Lebanon, a big mac would cost +30 dollars in Lebanon. I think there's something wrong with the dollar conversion rate as well as the local currency.

**Comment by roxwillis** [comment]
We are using a black market exchange rate for Lebanon: 22,000 per $. 
You can read more here: https://www.economist.com/finance-and-economics/2021/07/24/what-the-big-mac-index-says-about-the-dollar-and-the-dong
