### ISSUE TITLE
Where did the original data come from?

### ISSUE THREAD

**Issue by ncclementi** [TheEconomist/big-mac-data#3]
This repo is great, I might use some of the data to teach a class. 

I have a quick question, where did the original data come from? 
In other words how did you obtain the `big-mac-source-data.csv` file. 

Thanks

**Comment by futuraprime** [comment]
We're glad you like it! Please let us know if you use the data in your teaching.

The sources are listed in our [codebook](https://github.com/TheEconomist/big-mac-data#codebook). Specifically: the Big Mac prices are from McDonalds and from our own reporting, exchange rates are from Reuters, and GDP data is from the IMF. (Everything else is calculated from these data.)
